import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineVars({
	bg: "var(--color-bg)",
	bgSubtle: "var(--color-bg-subtle)",
	bgMuted: "var(--color-bg-muted)",
	text: "var(--color-text)",
	textSecondary: "var(--color-text-secondary)",
	textMuted: "var(--color-text-muted)",
	textBody: "var(--color-text-body)",
	border: "var(--color-border)",
	borderStrong: "var(--color-border-strong)",
	accentWriting: "var(--color-accent-writing)",
	accentWritingBg: "var(--color-accent-writing-bg)",
	accentThoughts: "var(--color-accent-thoughts)",
	accentThoughtsBg: "var(--color-accent-thoughts-bg)",
	success: "var(--color-success)",
	danger: "var(--color-danger)",
	warning: "var(--color-warning)",
	info: "var(--color-info)",
	follow: "var(--color-follow)",
	onAccent: "var(--color-on-accent)",
	terminal: "var(--color-terminal)",
	terminalMuted: "var(--color-terminal-muted)",
	terminalBorder: "var(--color-terminal-border)",
	onTerminal: "var(--color-on-terminal)",
	onTerminalMuted: "var(--color-on-terminal-muted)",
	catAi: "var(--color-cat-ai)",
	catDesign: "var(--color-cat-design)",
	catProduct: "var(--color-cat-product)",
	catEngineering: "var(--color-cat-engineering)",
	catProductivity: "var(--color-cat-productivity)",
	catLearning: "var(--color-cat-learning)",
	catOpensource: "var(--color-cat-opensource)",
	catThoughts: "var(--color-cat-thoughts)",
	catWork: "var(--color-cat-work)",
	catTools: "var(--color-cat-tools)",
	catDefault: "var(--color-cat-default)",
	ctaYellow: "var(--color-cta-yellow)",
	ctaRed: "var(--color-cta-red)",
	ctaOrange: "var(--color-cta-orange)",
	ctaPink: "var(--color-cta-pink)",
	ctaIndigo: "var(--color-cta-indigo)",
	ctaTeal: "var(--color-cta-teal)",
	ctaCyan: "var(--color-cta-cyan)",
	ctaLime: "var(--color-cta-lime)",
	ctaBlue: "var(--color-cta-blue)",
	ctaGreen: "var(--color-cta-green)",
	ctaPurple: "var(--color-cta-purple)",
	ctaGray: "var(--color-cta-gray)",
	ctaAmber: "var(--color-cta-amber)",
	ctaDefault: "var(--color-cta-default)",
	highlightYellow: "var(--color-highlight-yellow)",
	highlightGreen: "var(--color-highlight-green)",
	highlightPink: "var(--color-highlight-pink)",
	highlightBlue: "var(--color-highlight-blue)",
	shipEmpty: "var(--color-ship-empty)",
	shipLow: "var(--color-ship-low)",
	shipMid: "var(--color-ship-mid)",
	shipHigh: "var(--color-ship-high)",
	ds100: "var(--ds-gray-100)",
	ds200: "var(--ds-gray-200)",
	ds1000: "var(--ds-gray-1000)",
	dsBg200: "var(--ds-background-200)",
});

export const space = stylex.defineVars({
	none: "0px",
	1: "0.25rem",
	2: "0.5rem",
	3: "0.75rem",
	4: "1rem",
	5: "1.25rem",
	6: "1.5rem",
	8: "2rem",
	10: "2.5rem",
	12: "3rem",
	16: "4rem",
});

export const font = stylex.defineVars({
	body: "var(--font-body)",
	mono: "ui-monospace, SFMono-Regular, Menlo, monospace",
	regular: "var(--fw-regular)",
	medium: "var(--fw-medium)",
	semibold: "var(--fw-semibold)",
	bold: "var(--fw-bold)",
	xs: "var(--fs-xs)",
	sm: "var(--fs-sm)",
	base: "var(--fs-base)",
	lg: "var(--fs-lg)",
	xl: "var(--fs-xl)",
	"2xl": "var(--fs-2xl)",
	"4xl": "var(--fs-4xl)",
	"5xl": "var(--fs-5xl)",
	"7xl": "var(--fs-7xl)",
	trackingTight: "var(--tracking-tight)",
	trackingNormal: "var(--tracking-normal)",
	trackingWide: "var(--tracking-wide)",
	leadingTight: "var(--leading-tight)",
	leadingNormal: "var(--leading-normal)",
	leadingRelaxed: "var(--leading-relaxed)",
});

export const radius = stylex.defineVars({
	none: "0px",
	sm: "0.25rem",
	md: "0.375rem",
	lg: "0.5rem",
	xl: "0.75rem",
	"2xl": "1rem",
	full: "9999px",
});

export const shadow = stylex.defineVars({
	border: "var(--ds-shadow-border)",
	borderHover: "var(--ds-shadow-border-hover)",
});

export const motion = stylex.defineVars({
	fast: "150ms",
	normal: "200ms",
	slow: "300ms",
	easeOut: "cubic-bezier(0.2, 0, 0, 1)",
});
